export const Tabledata = {
  Pendingheader: [
    "User",
    "Risk Level",
    "Trigger Reason",
    "In queue for",
    "Date added on",
    "Previously reviewed",
  ],
  Pending: [
    {
      _id: 1,
      name: "Sam Altman",
      email: "samaltman123@gmail.com",
      level: "Medium",
      reason: "IP Change",
      days: "4 days",
      date: "12 Oct, 2023",
      conditionorname: "Yes",
      revieweddateormail: "23 Aug, 2023",
    },
    {
      _id: 2,
      name: "Sameer Choubey",
      email: "sameerchoubey123@gmail.com",
      level: "High",
      reason: "FIFO",
      days: "4 days",
      date: "12 Oct, 2023",
      conditionorname: "No",
    },
    {
      _id: 3,
      name: "Adarsh Panikkar",
      email: "adarsh@onjuno.com",
      level: "Low",
      reason: "IP Change",
      days: "5 days",
      date: "12 Oct, 2023",
      conditionorname: "No",
    },
    {
      _id: 4,
      name: "Pratik Shetty",
      email: "pratik3@gmail.com",
      level: "High",
      reason: "FIFO",
      days: "5 days",
      date: "12 Oct, 2023",
      conditionorname: "Yes",
      revieweddateormail: "12 Sep, 2023",
    },
    {
      _id: 5,
      name: "Elon Musk",
      email: "elon@twitterceo.com",
      level: "Low",
      reason: "FIFO",
      days: "5 days",
      date: "12 Oct, 2023",
      conditionorname: "Yes",
      revieweddateormail: "12 Sep, 2023",
    },
    {
      _id: 6,
      name: "Trina Kundu",
      email: "trina@onjuno.com",
      level: "Low",
      reason: "FIFO",
      days: "5 days",
      date: "12 Oct, 2023",
      conditionorname: "Yes",
      revieweddateormail: "12 Sep, 2023",
    },
  ],

  Completedheader: [
    "User",
    "Risk Level",
    "Action Reason",
    "Time to close",
    "Date added on",
    "Action taken by",
  ],
  Completed: [
    {
      _id: 1,
      name: "Sam Altman",
      email: "samaltman123@gmail.com",
      level: "Medium",
      reason: "Flagged",
      days: "14 days",
      date: "12 Oct, 2023",
      conditionorname: "Neil",
      revieweddateormail: "neil@onjuno.com",
    },
    {
      _id: 2,
      name: "Sameer Choubey",
      email: "sameerchoubey123@gmail.com",
      level: "High",
      reason: "Closed",
      days: "14 days",
      date: "12 Oct, 2023",
      conditionorname: "Pratik",
      revieweddateormail: "pratik@onjuno.com",
    },
    {
      _id: 3,
      name: "Adarsh Panikkar",
      email: "adarsh@onjuno.com",
      level: "Low",
      reason: "Closed",
      days: "15 days",
      date: "12 Oct, 2023",
      conditionorname: "Prashanth",
      revieweddateormail: "prashanth@onjuno.com",
    },
    {
      _id: 4,
      name: "Pratik Shetty",
      email: "pratik3@gmail.com",
      level: "High",
      reason: "SOI requested",
      days: "15 days",
      date: "12 Oct, 2023",
      conditionorname: "Rasleen Kaur",
      revieweddateormail: "rasleen@onjuno.com",
    },
    {
      _id: 5,
      name: "Elon Musk",
      email: "elon@twitterceo.com",
      level: "Low",
      reason: "Flagged",
      days: "15 days",
      date: "12 Oct, 2023",
      conditionorname: "Pratik Shetty",
      revieweddateormail: "pratik@onjuno.com",
    },
    {
      _id: 6,
      name: "Trina Kundu",
      email: "trina@onjuno.com",
      level: "Low",
      reason: "Closed",
      days: "15 days",
      date: "12 Oct, 2023",
      conditionorname: "Varun Deshpande ",
      revieweddateormail: "varun@onjuno.com",
    },
  ],
};


